In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
## Define the vocabulary size
voc_size=10000

In [12]:
one_hot_repre = [one_hot(words, voc_size) for words in sent]
one_hot_repre

[[7187, 5191, 9692, 433],
 [7187, 5191, 9692, 9569],
 [7187, 1972, 9692, 1620],
 [1033, 2499, 6516, 1244, 5343],
 [1033, 2499, 6516, 1244, 8446],
 [9977, 7187, 6251, 9692, 6183],
 [3777, 1781, 1646, 1244]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding 
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [20]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repre, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 7187 5191 9692  433]
 [   0    0    0    0 7187 5191 9692 9569]
 [   0    0    0    0 7187 1972 9692 1620]
 [   0    0    0 1033 2499 6516 1244 5343]
 [   0    0    0 1033 2499 6516 1244 8446]
 [   0    0    0 9977 7187 6251 9692 6183]
 [   0    0    0    0 3777 1781 1646 1244]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 148ms/step


array([[[-0.00315788,  0.00677015,  0.02517675,  0.01270412,
         -0.04610256,  0.02369327,  0.01978456, -0.04452179,
          0.01881951,  0.04448183],
        [-0.00315788,  0.00677015,  0.02517675,  0.01270412,
         -0.04610256,  0.02369327,  0.01978456, -0.04452179,
          0.01881951,  0.04448183],
        [-0.00315788,  0.00677015,  0.02517675,  0.01270412,
         -0.04610256,  0.02369327,  0.01978456, -0.04452179,
          0.01881951,  0.04448183],
        [-0.00315788,  0.00677015,  0.02517675,  0.01270412,
         -0.04610256,  0.02369327,  0.01978456, -0.04452179,
          0.01881951,  0.04448183],
        [ 0.04339601,  0.01926472, -0.03270793, -0.03574301,
          0.00533003,  0.00203013,  0.00270767,  0.02193462,
         -0.03389188, -0.02236351],
        [ 0.00058347, -0.03785906,  0.0005638 ,  0.01045873,
          0.04028703, -0.02850165, -0.03620174,  0.03196872,
          0.01539481, -0.03257027],
        [-0.01240662,  0.03071599,  0.02851403, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 7187, 5191, 9692,  433])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 32ms/step


array([[-0.00315788,  0.00677015,  0.02517675,  0.01270412, -0.04610256,
         0.02369327,  0.01978456, -0.04452179,  0.01881951,  0.04448183],
       [-0.00315788,  0.00677015,  0.02517675,  0.01270412, -0.04610256,
         0.02369327,  0.01978456, -0.04452179,  0.01881951,  0.04448183],
       [-0.00315788,  0.00677015,  0.02517675,  0.01270412, -0.04610256,
         0.02369327,  0.01978456, -0.04452179,  0.01881951,  0.04448183],
       [-0.00315788,  0.00677015,  0.02517675,  0.01270412, -0.04610256,
         0.02369327,  0.01978456, -0.04452179,  0.01881951,  0.04448183],
       [ 0.04339601,  0.01926472, -0.03270793, -0.03574301,  0.00533003,
         0.00203013,  0.00270767,  0.02193462, -0.03389188, -0.02236351],
       [ 0.00058347, -0.03785906,  0.0005638 ,  0.01045873,  0.04028703,
        -0.02850165, -0.03620174,  0.03196872,  0.01539481, -0.03257027],
       [-0.01240662,  0.03071599,  0.02851403, -0.02032857,  0.02370072,
         0.0342003 , -0.0323025 ,  0.02457805